apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    creator: norman
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /data2/nfs
    server: 192.168.13.36
  persistentVolumeReclaimPolicy: Retain
