apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
#  annotations:
     #配置默认的StorageClass,PVC创建无需指定SCName
#    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: jevic-nfs-storage
parameters:
  archiveOnDelete: "false"
